this concludes our evaluation for the baseline
crim-ca/pavics-jupyter-images pull request #18
Opened 2023-07-10 17:58 UTC by TimeaBagosiCrim

- add nervaluate results
- fix manually calculated scores
- fix ner handling details
- can tag this as the final baseline v1 of the NLU

2023-07-19 14:51 UTC, fmigneault commented
@TimeaBagosiCrim Can you fix the flagged file conflicts?

2023-07-19 14:52 UTC, fmigneault requested changes
Just need to fix the file conflicts to allow merge.

2023-07-31 10:53 UTC, TimeaBagosiCrim commented
@fmigneault  ready to merge

2023-09-13 16:35 UTC, fmigneault approved these changes

2023-09-13 17:27 UTC, merged